# Generated by Django 5.2.4 on 2025-08-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo_app', '0005_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='paymentstatus',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
